### PR TITLE
Fix typos + formatting

### PR DESCRIPTION
**Pull request by deepcharles**
Be careful of copy-paste from pdf to text files.

Nice CV!

### CODE REVIEW

**Comment by deepcharles** [comment]
It would be great if @simonrabate could take a look at this PR and merge it.

**Comment by deepcharles** [comment]
Any news on this issue?

**Comment by deepcharles** [comment]
Maybe @adabbas

**Comment by adabbas** [comment]
No news, I hope @simonrabate is all right !

**Comment by simonrabate** [comment]
@deepcharles this is done

**Pull request merged**
